use prueba_db;

CREATE TABLE hotel(
	CODE_HOTEL INTEGER PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	UBICACION VARCHAR(200) NOT NULL
)

CREATE TABLE cliente(
	IDENTIDAD VARCHAR(13) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(200) NOT NULL
)

CREATE TABLE boleto(
	CODIGO VARCHAR(6) PRIMARY KEY NOT NULL,
	NO_VUELO VARCHAR(100) NOT NULL,
	FECHA VARCHAR(200) NOT NULL,
	DESTINO VARCHAR(200) NOT NULL
)

CREATE TABLE aerolina(
	CODIGO VARCHAR(6) PRIMARY KEY NOT NULL,
	DESCUENTO INTEGER NOT NULL
)

CREATE TABLE reserva(
	id INT IDENTITY(1,1) PRIMARY KEY,
	fecha_in DATE NOT NULL,
	fecha_out DATE NOT NULL,
	CANTIDAD_PERSONAS INT DEFAULT 0
)

/*ALTER TABLES LLAVES FORANEAS */
ALTER TABLE reserva 
	ADD CONSTRAINT fk_cliente
		FOREIGN KEY (IDENTIDAD) REFERENCES cliente(IDENTIDAD)

ALTER TABLE reserva 
	ADD CONSTRAINT fk_reserva_hotel
	FOREIGN KEY (CODE_HOTEL) REFERENCES hotel(CODE_HOTEL)

ALTER TABLE boleto 
	ADD CONSTRAINT fk_tarifa_aerolina
	FOREIGN KEY (CODIGO) REFERENCES aerolina(CODIGO)

ALTER TABLE boleto 
	ADD CONSTRAINT fk_adquiere_cliente
	FOREIGN KEY (IDENTIDAD) REFERENCES cliente(IDENTIDAD)

/*ALTER TABLES CONDICIONES DE REGISTROS */

ALTER TABLE reserva ADD CONSTRAINT df_cantidad_personas DEFAULT 0 FOR CANTIDAD_PERSONAS;
ALTER TABLE boleto ADD CONSTRAINT ck_destino CHECK (DESTINO IN ('MEXICO','GUATEMALA','PANAMA'))
ALTER TABLE aerolina ADD CHECK (DESCUENTO>=10);
